# LAB2_2021389_DNN
## Task_01

In [1]:
import numpy as np

In [18]:
# inputs = [0.2,0.3]
# weights = [[0.1,0.2],[0.4,0.5]]
# bias = [0.6,0.4]

def initialize_parameters(input_dim, hidden_dim, output_dim):
    weights_hidden = np.random.rand(input_dim, hidden_dim)
    bias_hidden = np.random.rand(1, hidden_dim)
    weights_output = np.random.rand(hidden_dim, output_dim)
    bias_output = np.random.rand(1, output_dim)
    return weights_hidden, bias_hidden, weights_output, bias_output

input_dim = 2
hidden_dim = 2
output_dim = 1

weights_hidden, bias_hidden, weights_output, bias_output = initialize_parameters(input_dim, hidden_dim, output_dim)
weights_output

array([[0.19242267],
       [0.75256253]])

In [21]:
# activation functions
def sigmoid(x):
    return 1/(1+np.exp(-x))

def relu(z):
    """ReLU neuron"""
    return np.maximum(0, z)

## Task_02

In [7]:
# hidden layer neuron outputs
# h_n1 = inputs[0]*weights[0][0] + inputs[0]*weights[0][1] + bias[0]
# h_n2 = inputs[1]*weights[1][0] + inputs[1]*weights[1][1] + bias[1]

In [9]:
# # hidden layer neuron activation funcs.
# h_o1 = sigmoid(h_n1)
# h_o2 = sigmoid(h_n2)

# # bias on output neurons
# o_bias = 0.2

# # weights taken by hidden layer's neurons to output layer
# o_weight = [0.7,0.5]

In [6]:
# output = h_o1*o_weight[0] + h_o2*o_weight[1] + o_bias
# print("Output:",output)
# print('Final output after activation func. : ',relu(output))

Output: 0.992233851517446
Final output after activation func. :  0.992233851517446


In [22]:
def forward_propagation(X, weights_hidden, bias_hidden, weights_output, bias_output):
    hidden_activation = sigmoid(np.dot(X, weights_hidden) + bias_hidden)
    output = sigmoid(np.dot(hidden_activation, weights_output) + bias_output)
    return hidden_activation, output


## Task_03

In [23]:
# Loss Function
def mean_squared_error(y_true, y_pred):
    mse = np.mean((y_true - y_pred) ** 2)
    return mse

## Task_04

In [12]:
# Hyperparameters
learning_rate = 0.1
num_epochs = 50
batch_size = 20

## Task_05

In [26]:
def sigmoid_derivative(x):
    return x * (1 - x)

def backward_propagation(X, y, hidden_activation, output, weights_output):
    output_error = 2 * (output - y) * sigmoid_derivative(output)
    d_weights_output = np.dot(hidden_activation.T, output_error)
    d_bias_output = np.sum(output_error, axis=0, keepdims=True)

    hidden_error = np.dot(output_error, weights_output.T) * sigmoid_derivative(hidden_activation)
    d_weights_hidden = np.dot(X.reshape(1, -1).T, hidden_error)  # Reshape X for proper dot product
    d_bias_hidden = hidden_error

    return d_weights_hidden, d_bias_hidden, d_weights_output, d_bias_output

def update_weights(weights_hidden, bias_hidden, weights_output, bias_output, d_weights_hidden, d_bias_hidden, d_weights_output, d_bias_output, learning_rate):
    weights_hidden -= learning_rate * d_weights_hidden
    bias_hidden -= learning_rate * d_bias_hidden
    weights_output -= learning_rate * d_weights_output
    bias_output -= learning_rate * d_bias_output
    return weights_hidden, bias_hidden, weights_output, bias_output

## Task_06

In [27]:
# XOR problem dataset
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Training loop
for epoch in range(num_epochs):
    total_loss = 0
    for i in range(len(X)):
        # Forward propagation
        hidden_activation, output = forward_propagation(X[i], weights_hidden, bias_hidden, weights_output, bias_output)
        
        # Compute loss
        loss = mean_squared_error(y[i], output)
        total_loss += loss

        # Backward propagation
        d_weights_hidden, d_bias_hidden, d_weights_output, d_bias_output = backward_propagation(X[i], y[i], hidden_activation, output, weights_output)

        # Update weights
        weights_hidden, bias_hidden, weights_output, bias_output = update_weights(weights_hidden, bias_hidden, weights_output, bias_output, d_weights_hidden, d_bias_hidden, d_weights_output, d_bias_output, learning_rate)

    # Print average loss for the epoch
    if (epoch + 1) % 100 == 0:
        avg_loss = total_loss / len(X)
        print(f"Epoch {epoch + 1}, Average Loss: {avg_loss:.6f}")

# Final output for XOR dataset
print("Final outputs for XOR dataset:")
for i in range(len(X)):
    _, output = forward_propagation(X[i], weights_hidden, bias_hidden, weights_output, bias_output)
    print(f"Input: {X[i]}, Predicted Output: {output}")

Final outputs for XOR dataset:
Input: [0 0], Predicted Output: [[0.51536608]]
Input: [0 1], Predicted Output: [[0.50155733]]
Input: [1 0], Predicted Output: [[0.50724056]]
Input: [1 1], Predicted Output: [[0.49874157]]


In [17]:
# Print weights of each neuron
def print_weights(weights_hidden, weights_output):
    print("Weights (Hidden Layer):")
    print(weights_hidden)
    print("Weights (Output Layer):")
    print(weights_output)

# Print weights every 10 epochs
if (epoch + 1) % 10 == 0:
    print_weights(weights_hidden, weights_output)


## Task_07

In [33]:
# Print weights of each neuron
def print_weights(weights_hidden, weights_output):
    print("Weights (Hidden Layer):")
    print(weights_hidden)
    print("Weights (Output Layer):")
    print(weights_output)

# Print weights after training
print("Weights after training:")
print_weights(weights_hidden, weights_output)

Weights after training:
Weights (Hidden Layer):
[[0.86784222 0.63028075]
 [0.84563358 0.01209098]]
Weights (Output Layer):
[[-0.32186108]
 [ 0.19239309]]
